fix(cli): ImplementAvroSchema doesn't roundtrip through Display and clap::ValueEnum
Without this fix the CLI will always fail if `--impl-schemas` is not set:
```
error: invalid value 'None' for '--impl-schemas <METHOD>'
  [possible values: derive, copy-build-schema, none]

  tip: a similar value exists: 'none'

For more information, try '--help'.
```

This is because of the following bit from the Clap docs:
- `default_value_t [= <expr>]`: `Arg::default_value` and `Arg::required(false)`
  - Requires `std::fmt::Display` that roundtrips correctly with the `Arg::value_parser` or `#[arg(value_enum)]`
  - Without `<expr>`, relies on `Default::default()`